style="blue"
indent=4
margin=92
always_for_in="nothing"
for_in_replacement="âˆˆ"
whitespace_typedefs=false
import_to_using=true
whitespace_in_kwargs=false
align_struct_field=true
align_assignment=false
align_conditional=true
align_pair_arrow=false
normalize_line_endings="unix"
align_matrix=true
join_lines_based_on_source=true
indent_submodule=true
surround_whereop_typeparameters=false
yas_style_nesting=true
trailing_comma=false
short_to_long_function_def=false
conditional_to_if=false
